ContentTypeIdentifier:
    type: enum
    config:
        values:
            article:
                description: 'No description available'
            folder:
                description: 'No description available'
            user:
                description: 'No description available'
            user_group:
                description: 'No description available'
            file:
                description: 'No description available'
            image:
                description: 'No description available'
