DomainGroupMedia:
    type: object
    inherits:
        - DomainContentTypeGroup
    config:
        fields:
            _types:
                type: DomainGroupMediaTypes
                resolve: {  }
            files:
                type: FileContentConnection
                description: 'No description available'
                resolve: '@=resolver("SearchContentOfTypeAsConnection", ["file", args])'
                argsBuilder: 'Relay::Connection'
                args:
                    query: { type: ContentSearchQuery, description: 'A Content query used to filter results' }
                    sortBy: { type: '[SortByOptions]', description: 'A Sort Clause, or array of Clauses. Add _desc after a Clause to reverse it' }
            file:
                type: FileContent
                description: 'No description available'
                resolve: '@=resolver("DomainContentItem", [args, "file"])'
                args:
                    id: { type: Int, description: 'Content ID of the file' }
                    remoteId: { type: String, description: 'Content remote ID of the file' }
                    locationId: { type: Int, description: 'Location ID of the file' }
            images:
                type: ImageContentConnection
                description: 'No description available'
                resolve: '@=resolver("SearchContentOfTypeAsConnection", ["image", args])'
                argsBuilder: 'Relay::Connection'
                args:
                    query: { type: ContentSearchQuery, description: 'A Content query used to filter results' }
                    sortBy: { type: '[SortByOptions]', description: 'A Sort Clause, or array of Clauses. Add _desc after a Clause to reverse it' }
            image:
                type: ImageContent
                description: 'No description available'
                resolve: '@=resolver("DomainContentItem", [args, "image"])'
                args:
                    id: { type: Int, description: 'Content ID of the image' }
                    remoteId: { type: String, description: 'Content remote ID of the image' }
                    locationId: { type: Int, description: 'Location ID of the image' }
