FileContentCreateInput:
    type: input-object
    config:
        fields:
            name:
                type: String!
            description:
                type: RichTextFieldInput
            file:
                type: BinaryFieldInput!
