ImageContentCreateInput:
    type: input-object
    config:
        fields:
            name:
                type: String!
            caption:
                type: RichTextFieldInput
            image:
                type: ImageFieldInput
