ImageContent:
    type: object
    inherits:
        - AbstractDomainContent
    config:
        interfaces:
            - DomainContent
            - Node
        fields:
            name:
                type: String
                resolve: '@=resolver("DomainFieldValue", [value, "name"])'
            caption:
                type: RichTextFieldValue
                resolve: '@=resolver("DomainFieldValue", [value, "caption"])'
            image:
                type: ImageFieldValue
                resolve: '@=resolver("DomainFieldValue", [value, "image"])'
