services:
  _defaults:
    public: false
  _cr.admin_tabs.ezdataflow_group:
    parent: EzSystems\EzPlatformAdminUi\Component\TabsComponent
    autowire: true
    autoconfigure: false
    public: false
    arguments:
      $template: '@@ezdesign/ezdataflow/parts/tab/ezdataflow.html.twig'
      $groupIdentifier: 'coderhapsodie-ezdataflow'
    tags:
      - { name: ezplatform.admin_ui.component, group: 'coderhapsodie-ezdataflow' }
